#!/usr/bin/env bash
# clarion-up.sh — single entry to start the Clarion browser-extension demo.
#
# Brings up everything for the live run in one command:
#   1. mints a fresh human LiveKit token (offline, from agent/.env) and writes the
#      gitignored web/extension/config.js (LIVEKIT_URL + ROOM_NAME + TOKEN);
#   2. starts the ALWAYS-ON relay broker — the tab bridge — which binds 8771
#      (extension) + 8773 (agent) at BOOT, before any shortcut/mic/dispatch, so
#      the extension can always reach it (the broker is independent of voice);
#   3. starts the LiveKit voice worker (CLARION_ACTUATOR=extension), whose actuator
#      now reaches the tab THROUGH the broker as a client (it never binds 8771);
#   4. launches Chrome with the extension loaded, the debugger banner suppressed,
#      a DURABLE dedicated profile (logins persist across runs; does not touch your
#      main Chrome), and a CDP port so Playwright can OBSERVE the tab on demand —
#      the shared cockpit. NB: a live CDP session and the extension's chrome.debugger
#      cannot share one tab, so observe via CDP only while the extension is idle
#      (login/browse); read the LOG FILES while it drives.
#
# Then: press Ctrl/Cmd+Shift+Y on a tab to attach. Stop with scripts/clarion-down.sh.
#
# Usage:  scripts/clarion-up.sh [START_URL]
#   START_URL — the tab to open (default a blank gov-portal search start). Read-only
#               up to the auth wall — no credentials, no submit (§9 recording rules).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENT="$ROOT/agent"
EXT="$ROOT/web/extension"
PY="$AGENT/.venv/bin/python"
ROOM="${CLARION_ROOM:-clarion-hero}"
START_URL="${1:-https://www.usa.gov/benefits}"
# Durable profile (logins persist across runs/reboots — unlike the old /tmp one).
# Override with CLARION_CHROME_PROFILE; CDP port lets Playwright observe on demand.
PROFILE="${CLARION_CHROME_PROFILE:-$HOME/.clarion/chrome-profile-durable}"
CDP_PORT="${CLARION_CDP_PORT:-9222}"
WORKER_LOG="/tmp/clarion-worker.log"
WORKER_PID_FILE="/tmp/clarion-worker.pid"
BROKER_LOG="/tmp/clarion-broker.log"
BROKER_PID_FILE="/tmp/clarion-broker.pid"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

echo "== Clarion up =="
[ -x "$PY" ] || { echo "!! venv python missing at $PY — run: cd agent && pip install -e '.[spike]' && pip install -e '.[retrieval]'"; exit 1; }
[ -f "$AGENT/.env" ] || { echo "!! agent/.env missing"; exit 1; }

# 1. Mint the human token (offline) + write config.js -------------------------
echo "[1/4] minting human token for room '$ROOM' + writing config.js…"
TOKEN="$(CLARION_ROOM="$ROOM" AGENT_ENV="$AGENT/.env" "$PY" - <<'PY'
import os
from dotenv import load_dotenv
load_dotenv(os.environ["AGENT_ENV"])
from livekit import api
room = os.environ["CLARION_ROOM"]
tok = (api.AccessToken(os.environ["LIVEKIT_API_KEY"], os.environ["LIVEKIT_API_SECRET"])
       .with_identity("human")
       .with_grants(api.VideoGrants(room_join=True, room=room, can_publish=True, can_subscribe=True))
       .to_jwt())
print(tok)
PY
)"
LK_URL="$(grep -E '^LIVEKIT_URL=' "$AGENT/.env" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")"
cat > "$EXT/config.js" <<JS
// generated by scripts/clarion-up.sh — gitignored, do not commit.
export default {
  LIVEKIT_URL: "$LK_URL",
  ROOM_NAME: "$ROOM",
  TOKEN: "$TOKEN",
};
JS
echo "      wrote $EXT/config.js (url + room '$ROOM' + fresh token)"

# If a previous stack is holding any relay port, clear it before a fresh start.
if lsof -ti tcp:8771 >/dev/null 2>&1 || lsof -ti tcp:8773 >/dev/null 2>&1; then
  echo "[2/4] relay ports busy — clearing the old stack first…"
  "$ROOT/scripts/clarion-down.sh" >/dev/null 2>&1 || true
  sleep 1
fi

# Rotate logs → *.prev so THIS session starts with clean logs (a session never
# reads stale lines from the last run — appended logs cost real debug time). One
# previous generation is kept. Services below open fresh files.
echo "[*] rotating logs → *.prev (fresh logs for this session)"
for LOG in "$WORKER_LOG" "$BROKER_LOG" /tmp/clarion-ext.log /tmp/clarion-logsink.out; do
  [ -f "$LOG" ] && mv -f "$LOG" "$LOG.prev" 2>/dev/null || true
done

# 2a. Always-on browser-log sink (extension SW/HUD → /tmp/clarion-ext.log) -----
# Lets logs be READ directly (tail -f) instead of copy-pasted out of DevTools.
if ! lsof -ti tcp:8772 >/dev/null 2>&1; then
  nohup "$PY" "$ROOT/scripts/clarion-logsink.py" >/tmp/clarion-logsink.out 2>&1 &
  echo $! >/tmp/clarion-logsink.pid
  echo "[2/4] browser-log sink on :8772 → tail -f /tmp/clarion-ext.log"
fi

# 2b. Always-on relay BROKER — the tab bridge, bound at BOOT (the decoupling) --
# Binds 8771 (extension; FROZEN wire) + 8773 (agent client) independent of voice,
# so the extension can attach the moment the user presses the shortcut — no mic,
# no dispatch, no waiting. This is what fixes "relay only opens on dispatch".
echo "[2/4] starting the relay broker (ext :8771 / agent :8773)…"
( cd "$AGENT" && nohup "$PY" -m clarion.actuator.relay_broker >"$BROKER_LOG" 2>&1 & echo $! >"$BROKER_PID_FILE" )
for _ in $(seq 1 20); do
  lsof -nP -iTCP:8771 -sTCP:LISTEN >/dev/null 2>&1 && break
  sleep 0.25
done
if lsof -nP -iTCP:8771 -sTCP:LISTEN >/dev/null 2>&1; then
  echo "      broker UP — 8771 LISTENING now (tab bridge open before any shortcut/mic)"
else
  echo "!! broker failed to bind 8771 — last lines of $BROKER_LOG:"; tail -15 "$BROKER_LOG"; exit 1
fi

# 3. Start the LiveKit voice worker (reaches the tab THROUGH the broker) -------
echo "[3/4] starting the voice worker (LiveKit agent; actuator → broker client)…"
( cd "$AGENT" && CLARION_ACTUATOR=extension nohup "$PY" -m clarion.app.voice_entry dev >"$WORKER_LOG" 2>&1 & echo $! >"$WORKER_PID_FILE" )
sleep 4
if kill -0 "$(cat "$WORKER_PID_FILE" 2>/dev/null)" 2>/dev/null; then
  echo "      worker PID $(cat "$WORKER_PID_FILE") — log: $WORKER_LOG"
  grep -iE "registered worker|see tracing information" "$WORKER_LOG" | tail -2 || true
else
  echo "!! worker exited early — last lines of $WORKER_LOG:"; tail -15 "$WORKER_LOG"; exit 1
fi

# 4. Launch Chrome with the extension + debugger flag -------------------------
echo "[4/4] launching Chrome (dedicated profile; extension loaded; banner suppressed)…"
# If a Chrome is already running on this profile, a new launch just opens a tab in
# it and SILENTLY IGNORES these flags (no fresh extension, no CDP) — warn loudly.
if lsof -nP -iTCP:"$CDP_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
  echo "      NOTE: :$CDP_PORT already listening — a Chrome on this profile is likely up;"
  echo "            its flags won't refresh. Quit that Chrome first for a clean relaunch."
fi
if [ -x "$CHROME" ]; then
  "$CHROME" --user-data-dir="$PROFILE" \
    --remote-debugging-port="$CDP_PORT" \
    "--remote-allow-origins=*" \
    --silent-debugger-extension-api \
    --load-extension="$EXT" \
    --disable-features=DisableLoadExtensionCommandLineSwitch \
    --no-first-run --no-default-browser-check \
    "$START_URL" >/tmp/clarion-chrome.log 2>&1 &
  echo "      Chrome launched → $START_URL (profile: $PROFILE · CDP: http://localhost:$CDP_PORT)"
else
  echo "!! Chrome not at $CHROME — open it yourself with:"
  echo "   '$CHROME' --user-data-dir=$PROFILE --remote-debugging-port=$CDP_PORT --remote-allow-origins='*' --silent-debugger-extension-api --load-extension=$EXT $START_URL"
fi

cat <<NEXT

== ready ==
  • The tab bridge (broker) is ALREADY listening on :8771 — press Ctrl/Cmd+Shift+Y
    on the tab to attach (no need to wait for voice/mic; that's the whole point).
  • Grant the mic if 'request-mic' opens (voice only — the relay works without it).
  • If the extension didn't auto-load: chrome://extensions → Developer mode → Load unpacked → $EXT
  • Observe login state:      Playwright connect_over_cdp("http://localhost:$CDP_PORT")
                              — ONLY while the extension is idle (before the shortcut).
  • Watch the broker:         tail -f $BROKER_LOG
  • Watch the agent attach:   tail -f $WORKER_LOG
  • Watch the browser side:   tail -f /tmp/clarion-ext.log
  • Stop everything:          scripts/clarion-down.sh
  Read-only up to the auth wall — no credentials, no submit.
NEXT
