#!/usr/bin/env bash
# clarion-up.sh — single entry to start the Clarion browser-extension demo.
#
# Brings up everything for the live run in one command:
#   1. mints a fresh human LiveKit token (offline, from agent/.env) and writes the
#      gitignored web/extension/config.js (LIVEKIT_URL + ROOM_NAME + TOKEN);
#   2. starts the ALWAYS-ON relay broker — the tab bridge — which binds 8771
#      (extension) + 8773 (agent) at BOOT, before any shortcut/mic/dispatch, so
#      the extension can always reach it (the broker is independent of voice);
#   3. starts the LiveKit voice worker (CLARION_ACTUATOR=extension), whose actuator
#      now reaches the tab THROUGH the broker as a client (it never binds 8771);
#   4. launches Google Chrome for Testing (branded Chrome DROPPED --load-extension;
#      its CDP replacement needs --remote-debugging-pipe, which kills our port) with
#      the extension AUTO-loaded, the debugger banner suppressed,
#      a DURABLE dedicated profile (logins persist across runs; does not touch your
#      main Chrome), and a CDP port so Playwright can OBSERVE the tab on demand —
#      the shared cockpit. NB: a live CDP session and the extension's chrome.debugger
#      cannot share one tab, so observe via CDP only while the extension is idle
#      (login/browse); read the LOG FILES while it drives.
#
# Then: press Ctrl/Cmd+Shift+Y on a tab to attach. Stop with scripts/clarion-down.sh.
#
# Usage:  scripts/clarion-up.sh [START_URL]
#   START_URL — the tab to open (default a blank gov-portal search start). Read-only
#               up to the auth wall — no credentials, no submit (§9 recording rules).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENT="$ROOT/agent"
EXT="$ROOT/web/extension"
PY="$AGENT/.venv/bin/python"
ROOM="${CLARION_ROOM:-clarion-hero}"
START_URL="${1:-https://www.usa.gov/benefits}"
# Durable profile (logins persist across runs/reboots — unlike the old /tmp one).
# Override with CLARION_CHROME_PROFILE; CDP port lets Playwright observe on demand.
# Default profile is the Chrome-for-Testing one (the primary browser below).
PROFILE="${CLARION_CHROME_PROFILE:-$HOME/.clarion/chromium-profile-durable}"
CDP_PORT="${CLARION_CDP_PORT:-9222}"
WORKER_LOG="/tmp/clarion-worker.log"
WORKER_PID_FILE="/tmp/clarion-worker.pid"
BROKER_LOG="/tmp/clarion-broker.log"
BROKER_PID_FILE="/tmp/clarion-broker.pid"
CHROME_BRANDED="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"  # manual-load fallback only

echo "== Clarion up =="
[ -x "$PY" ] || { echo "!! venv python missing at $PY — run: cd agent && pip install -e '.[spike]' && pip install -e '.[retrieval]'"; exit 1; }
[ -f "$AGENT/.env" ] || { echo "!! agent/.env missing"; exit 1; }

# 1. Mint the human token (offline) + write config.js -------------------------
echo "[1/4] minting human token for room '$ROOM' + writing config.js…"
TOKEN="$(CLARION_ROOM="$ROOM" AGENT_ENV="$AGENT/.env" "$PY" - <<'PY'
import os
from dotenv import load_dotenv
load_dotenv(os.environ["AGENT_ENV"])
from livekit import api
room = os.environ["CLARION_ROOM"]
tok = (api.AccessToken(os.environ["LIVEKIT_API_KEY"], os.environ["LIVEKIT_API_SECRET"])
       .with_identity("human")
       .with_grants(api.VideoGrants(room_join=True, room=room, can_publish=True, can_subscribe=True))
       .to_jwt())
print(tok)
PY
)"
LK_URL="$(grep -E '^LIVEKIT_URL=' "$AGENT/.env" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")"
cat > "$EXT/config.js" <<JS
// generated by scripts/clarion-up.sh — gitignored, do not commit.
export default {
  LIVEKIT_URL: "$LK_URL",
  ROOM_NAME: "$ROOM",
  TOKEN: "$TOKEN",
  // Optional mic override (label substring). Empty → offscreen auto-prefers a
  // real device over virtual ones (MMAudio/Teams/etc). Set CLARION_MIC_MATCH.
  MIC_MATCH: "${CLARION_MIC_MATCH:-}",
};
JS
echo "      wrote $EXT/config.js (url + room '$ROOM' + fresh token)"

# If a previous stack is holding any relay port, clear it before a fresh start.
if lsof -ti tcp:8771 >/dev/null 2>&1 || lsof -ti tcp:8773 >/dev/null 2>&1; then
  echo "[2/4] relay ports busy — clearing the old stack first…"
  "$ROOT/scripts/clarion-down.sh" >/dev/null 2>&1 || true
  sleep 1
fi

# Rotate logs → *.prev so THIS session starts with clean logs (a session never
# reads stale lines from the last run — appended logs cost real debug time). One
# previous generation is kept. Services below open fresh files.
echo "[*] rotating logs → *.prev (fresh logs for this session)"
for LOG in "$WORKER_LOG" "$BROKER_LOG" /tmp/clarion-ext.log /tmp/clarion-logsink.out; do
  [ -f "$LOG" ] && mv -f "$LOG" "$LOG.prev" 2>/dev/null || true
done

# 2a. Always-on browser-log sink (extension SW/HUD → /tmp/clarion-ext.log) -----
# Lets logs be READ directly (tail -f) instead of copy-pasted out of DevTools.
if ! lsof -ti tcp:8772 >/dev/null 2>&1; then
  nohup "$PY" "$ROOT/scripts/clarion-logsink.py" >/tmp/clarion-logsink.out 2>&1 &
  echo $! >/tmp/clarion-logsink.pid
  echo "[2/4] browser-log sink on :8772 → tail -f /tmp/clarion-ext.log"
fi

# 2b. Always-on relay BROKER — the tab bridge, bound at BOOT (the decoupling) --
# Binds 8771 (extension; FROZEN wire) + 8773 (agent client) independent of voice,
# so the extension can attach the moment the user presses the shortcut — no mic,
# no dispatch, no waiting. This is what fixes "relay only opens on dispatch".
echo "[2/4] starting the relay broker (ext :8771 / agent :8773)…"
( cd "$AGENT" && nohup "$PY" -m clarion.actuator.relay_broker >"$BROKER_LOG" 2>&1 & echo $! >"$BROKER_PID_FILE" )
for _ in $(seq 1 20); do
  lsof -nP -iTCP:8771 -sTCP:LISTEN >/dev/null 2>&1 && break
  sleep 0.25
done
if lsof -nP -iTCP:8771 -sTCP:LISTEN >/dev/null 2>&1; then
  echo "      broker UP — 8771 LISTENING now (tab bridge open before any shortcut/mic)"
else
  echo "!! broker failed to bind 8771 — last lines of $BROKER_LOG:"; tail -15 "$BROKER_LOG"; exit 1
fi

# 3. Start the LiveKit voice worker (reaches the tab THROUGH the broker) -------
echo "[3/4] starting the voice worker (LiveKit agent; actuator → broker client)…"
( cd "$AGENT" && CLARION_ACTUATOR=extension nohup "$PY" -m clarion.app.voice_entry dev >"$WORKER_LOG" 2>&1 & echo $! >"$WORKER_PID_FILE" )
sleep 4
if kill -0 "$(cat "$WORKER_PID_FILE" 2>/dev/null)" 2>/dev/null; then
  echo "      worker PID $(cat "$WORKER_PID_FILE") — log: $WORKER_LOG"
  grep -iE "registered worker|see tracing information" "$WORKER_LOG" | tail -2 || true
else
  echo "!! worker exited early — last lines of $WORKER_LOG:"; tail -15 "$WORKER_LOG"; exit 1
fi

# 4. Launch the browser with the extension auto-loaded ------------------------
# Branded Google Chrome REMOVED --load-extension (abuse vector); its CDP
# replacement Extensions.loadUnpacked needs --remote-debugging-pipe, which is
# incompatible with our CDP port. Playwright's "Google Chrome for Testing" still
# honors --load-extension → we launch THAT for true auto-load. Branded Chrome
# stays a manual-load fallback (Load unpacked persists in the durable profile).
echo "[4/4] launching the browser (Chrome for Testing; extension auto-loaded; CDP open)…"
# A browser already on this profile makes a new launch a no-op for these flags
# (it just opens a tab in the live instance) — warn loudly.
if lsof -nP -iTCP:"$CDP_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
  echo "      NOTE: :$CDP_PORT already listening — a browser on this profile is likely up;"
  echo "            its flags won't refresh. Quit it first for a clean relaunch."
fi
CFT="$("$PY" -c 'from playwright.sync_api import sync_playwright
with sync_playwright() as p: print(p.chromium.executable_path)' 2>/dev/null || true)"
if [ -n "$CFT" ] && [ -x "$CFT" ]; then
  "$CFT" --user-data-dir="$PROFILE" \
    --remote-debugging-port="$CDP_PORT" \
    "--remote-allow-origins=*" \
    --silent-debugger-extension-api \
    --load-extension="$EXT" \
    --no-first-run --no-default-browser-check \
    "$START_URL" >/tmp/clarion-chrome.log 2>&1 &
  echo "      Chrome for Testing launched → $START_URL"
  echo "      (profile: $PROFILE · CDP: http://localhost:$CDP_PORT · extension auto-loaded)"
elif [ -x "$CHROME_BRANDED" ]; then
  echo "      !! Chrome for Testing not found (run: $PY -m playwright install chromium)."
  echo "         Falling back to branded Chrome — it CANNOT auto-load the extension."
  "$CHROME_BRANDED" --user-data-dir="$PROFILE" \
    --remote-debugging-port="$CDP_PORT" \
    "--remote-allow-origins=*" \
    --silent-debugger-extension-api \
    --no-first-run --no-default-browser-check \
    "$START_URL" >/tmp/clarion-chrome.log 2>&1 &
  echo "      branded Chrome launched → load the extension ONCE: chrome://extensions →"
  echo "      Developer mode → Load unpacked → $EXT  (persists in the durable profile)."
else
  echo "!! no usable browser (Chrome for Testing or branded Chrome) — install one."
fi

cat <<NEXT

== ready — now STREAMING all logs in this window (Ctrl-C stops EVERYTHING) ==
  • On the tab: press Ctrl/Cmd+Shift+Y to attach, grant the mic, then TALK.
  • If the extension didn't auto-load: chrome://extensions → Developer mode → Load unpacked → $EXT
  • Lines below are tagged [worker] (agent/STT/LLM/TTS/tools/errors), [broker] (relay),
    [ext] (browser mic + HUD). Each line appears ONCE — worker lines are [worker] only;
    the on-page HUD still mirrors the important ones (clarion-log topic).
  • Ctrl-C in THIS window tears the whole stack down (same as scripts/clarion-down.sh).
  Read-only up to the auth wall — no credentials, no submit.
NEXT

# Stay in the FOREGROUND and stream every log, tagged + colored by source, until
# Ctrl-C — which tears the stack down (clean up/down semantics). errexit is off so a
# log rotation under tail can never kill the cockpit.
set +e
: >>"$WORKER_LOG"; : >>"$BROKER_LOG"; : >>/tmp/clarion-ext.log
_tail_tagged() { tail -n 8 -F "$1" 2>/dev/null | while IFS= read -r l; do printf '%s %s\n' "$2" "$l"; done; }
cleanup() {
  trap - INT TERM
  echo; echo "== Ctrl-C — shutting the Clarion stack down =="
  kill $(jobs -p) 2>/dev/null || true
  "$ROOT/scripts/clarion-down.sh" || true
  exit 0
}
trap cleanup INT TERM
# Kill orphaned cockpit tails from a prior `clarion-up`: clarion-down replaces the
# worker/broker, but `tail -F` survives the truncation and keeps re-emitting the
# SAME file — so without this every line would stream TWICE (once per stale tail).
# Drop them so each line streams exactly ONCE.
pkill -f "tail -n 8 -F /tmp/clarion-" 2>/dev/null || true
_tail_tagged "$WORKER_LOG"        "$(printf '\033[36m[worker]\033[0m')" &
_tail_tagged "$BROKER_LOG"        "$(printf '\033[33m[broker]\033[0m')" &
_tail_tagged /tmp/clarion-ext.log "$(printf '\033[32m[ext]\033[0m   ')" &
wait
