#!/usr/bin/env bash
# clarion-up.sh — single entry to start the Clarion browser-extension demo.
#
# Brings up everything for the live run in one command:
#   1. mints a fresh human LiveKit token (offline, from agent/.env) and writes the
#      gitignored web/extension/config.js (LIVEKIT_URL + ROOM_NAME + TOKEN);
#   2. starts the Python brain — the CDP relay (ws://127.0.0.1:8771) + the LiveKit
#      voice worker (CLARION_ACTUATOR=extension) — in the background;
#   3. launches Chrome with the extension loaded, the debugger banner suppressed,
#      and a dedicated profile (does not touch your main Chrome).
#
# Then: press Ctrl/Cmd+Shift+Y on a tab to attach. Stop with scripts/clarion-down.sh.
#
# Usage:  scripts/clarion-up.sh [START_URL]
#   START_URL — the tab to open (default a blank gov-portal search start). Read-only
#               up to the auth wall — no credentials, no submit (§9 recording rules).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENT="$ROOT/agent"
EXT="$ROOT/web/extension"
PY="$AGENT/.venv/bin/python"
ROOM="${CLARION_ROOM:-clarion-hero}"
START_URL="${1:-https://www.usa.gov/benefits}"
PROFILE="/tmp/clarion-chrome-profile"
WORKER_LOG="/tmp/clarion-worker.log"
WORKER_PID_FILE="/tmp/clarion-worker.pid"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

echo "== Clarion up =="
[ -x "$PY" ] || { echo "!! venv python missing at $PY — run: cd agent && pip install -e '.[spike]' && pip install -e '.[retrieval]'"; exit 1; }
[ -f "$AGENT/.env" ] || { echo "!! agent/.env missing"; exit 1; }

# 1. Mint the human token (offline) + write config.js -------------------------
echo "[1/3] minting human token for room '$ROOM' + writing config.js…"
TOKEN="$(CLARION_ROOM="$ROOM" AGENT_ENV="$AGENT/.env" "$PY" - <<'PY'
import os
from dotenv import load_dotenv
load_dotenv(os.environ["AGENT_ENV"])
from livekit import api
room = os.environ["CLARION_ROOM"]
tok = (api.AccessToken(os.environ["LIVEKIT_API_KEY"], os.environ["LIVEKIT_API_SECRET"])
       .with_identity("human")
       .with_grants(api.VideoGrants(room_join=True, room=room, can_publish=True, can_subscribe=True))
       .to_jwt())
print(tok)
PY
)"
LK_URL="$(grep -E '^LIVEKIT_URL=' "$AGENT/.env" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")"
cat > "$EXT/config.js" <<JS
// generated by scripts/clarion-up.sh — gitignored, do not commit.
export default {
  LIVEKIT_URL: "$LK_URL",
  ROOM_NAME: "$ROOM",
  TOKEN: "$TOKEN",
};
JS
echo "      wrote $EXT/config.js (url + room '$ROOM' + fresh token)"

# 2a. Always-on browser-log sink (extension SW/HUD → /tmp/clarion-ext.log) -----
# Lets logs be READ directly (tail -f) instead of copy-pasted out of DevTools.
if ! lsof -ti tcp:8772 >/dev/null 2>&1; then
  nohup "$PY" "$ROOT/scripts/clarion-logsink.py" >/tmp/clarion-logsink.out 2>&1 &
  echo $! >/tmp/clarion-logsink.pid
  echo "[2/3] browser-log sink on :8772 → tail -f /tmp/clarion-ext.log"
fi

# 2. Start the Python brain (relay + voice worker) ----------------------------
if lsof -ti tcp:8771 >/dev/null 2>&1; then
  echo "[2/3] port 8771 busy — stopping the stale worker first…"
  "$ROOT/scripts/clarion-down.sh" >/dev/null 2>&1 || true
  sleep 1
fi
echo "[2/3] starting the voice worker (relay :8771 + LiveKit agent)…"
( cd "$AGENT" && CLARION_ACTUATOR=extension nohup "$PY" -m clarion.app.voice_entry dev >"$WORKER_LOG" 2>&1 & echo $! >"$WORKER_PID_FILE" )
sleep 4
if kill -0 "$(cat "$WORKER_PID_FILE" 2>/dev/null)" 2>/dev/null; then
  echo "      worker PID $(cat "$WORKER_PID_FILE") — log: $WORKER_LOG"
  grep -iE "relay listening|registered worker|waiting for the extension" "$WORKER_LOG" | tail -2 || true
else
  echo "!! worker exited early — last lines of $WORKER_LOG:"; tail -15 "$WORKER_LOG"; exit 1
fi

# 3. Launch Chrome with the extension + debugger flag -------------------------
echo "[3/3] launching Chrome (dedicated profile; extension loaded; banner suppressed)…"
if [ -x "$CHROME" ]; then
  "$CHROME" --user-data-dir="$PROFILE" \
    --silent-debugger-extension-api \
    --load-extension="$EXT" \
    --disable-features=DisableLoadExtensionCommandLineSwitch \
    --no-first-run --no-default-browser-check \
    "$START_URL" >/tmp/clarion-chrome.log 2>&1 &
  echo "      Chrome launched → $START_URL"
else
  echo "!! Chrome not at $CHROME — open it yourself with:"
  echo "   '$CHROME' --user-data-dir=$PROFILE --silent-debugger-extension-api --load-extension=$EXT $START_URL"
fi

cat <<NEXT

== ready ==
  • Grant the mic if 'request-mic' opens, then press  Ctrl/Cmd+Shift+Y  on the tab to attach.
  • If the extension didn't auto-load: chrome://extensions → Developer mode → Load unpacked → $EXT
  • Watch the agent attach:   tail -f $WORKER_LOG
  • Stop everything:          scripts/clarion-down.sh
  Read-only up to the auth wall — no credentials, no submit.
NEXT
